apiVersion: apps/v1
kind: Deployment
metadata:
  name: blue
  labels:
    app: myapp
spec:
  selector:
    matchLabels:
      color: blue
  template:
    metadata:
      name: myapp-pod
      labels:
        color: blue
    spec:
      containers:
        - name: nginx-container
          image: nginx
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: color
                    operator: In
                    values:
                      - "blue"
  replicas: 3
    
